name: Lint Code

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install eslint
      - run: npx eslint 20250617-CI-CD-Docker-HW/03-app.js