name: Lint Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8 ONLY on these two files
        run: flake8 flask_app.py test_app.py